// <auto-generated />
using System;
using DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260203145106_UpdatedProjectAndContract")]
    partial class UpdatedProjectAndContract
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CategoryProject", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("integer")
                        .HasColumnName("categories_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("CategoriesId", "ProjectId")
                        .HasName("pk_projects_categories");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_projects_categories_project_id");

                    b.ToTable("projects_categories", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Auth.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<DateTime>("ExpiredDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_date")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("jwt_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Auth.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin",
                            Name = "admin"
                        },
                        new
                        {
                            Id = "employer",
                            Name = "employer"
                        },
                        new
                        {
                            Id = "freelancer",
                            Name = "freelancer"
                        });
                });

            modelBuilder.Entity("Domain.Models.Auth.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarImg")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("avatar_img");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalProvider")
                        .HasColumnType("text")
                        .HasColumnName("external_provider");

                    b.Property<string>("ExternalProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("external_provider_key");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_users_created_by");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("ix_users_modified_by");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_users_role_id");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 2, 3, 14, 51, 5, 751, DateTimeKind.Utc).AddTicks(2281),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            DisplayName = "Admin",
                            Email = "admin@mail.com",
                            ModifiedAt = new DateTime(2026, 2, 3, 14, 51, 5, 751, DateTimeKind.Utc).AddTicks(2288),
                            ModifiedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            PasswordHash = "73EA432F87B6CF53948DC072D78CCB601CD30F3C7D00546D1142C2A4571A4672-98C92CAE0B955542E285B668D6BC64D9",
                            RoleId = "admin"
                        });
                });

            modelBuilder.Entity("Domain.Models.Auth.Users.UserWallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("balance");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("currency");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.HasKey("Id")
                        .HasName("pk_user_wallets");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_user_wallets_created_by");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("ix_user_wallets_modified_by");

                    b.ToTable("user_wallets", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Auth.Users.WalletTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("TransactionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_date")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("transaction_type");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id")
                        .HasName("pk_wallet_transactions");

                    b.HasIndex("WalletId")
                        .HasDatabaseName("ix_wallet_transactions_wallet_id");

                    b.ToTable("wallet_transactions", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Countries.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alpha2Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("alpha2code");

                    b.Property<string>("Alpha3Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("alpha3code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_countries");

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Employers.Employer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("company_name");

                    b.Property<string>("CompanyWebsite")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("company_website");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_employers");

                    b.ToTable("employers", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Freelance.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AgreedRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("agreed_rate");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("EndDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("FreelancerId")
                        .HasColumnType("uuid")
                        .HasColumnName("freelancer_id");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_contracts");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_contracts_created_by");

                    b.HasIndex("FreelancerId")
                        .HasDatabaseName("ix_contracts_freelancer_id");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("ix_contracts_modified_by");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_contracts_project_id");

                    b.ToTable("contracts", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Freelance.ContractMilestone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_contract_milestones");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("ix_contract_milestones_contract_id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_contract_milestones_created_by");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("ix_contract_milestones_modified_by");

                    b.ToTable("contract_milestones", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Freelance.Freelancer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarLogo")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("avatar_logo");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("bio");

                    b.Property<int?>("CountryId")
                        .HasColumnType("integer")
                        .HasColumnName("country_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<decimal?>("HourlyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("hourly_rate");

                    b.Property<string>("Location")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("location");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_freelancers");

                    b.HasIndex("CountryId")
                        .HasDatabaseName("ix_freelancers_country_id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_freelancers_created_by");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("ix_freelancers_modified_by");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_freelancers_user_id");

                    b.ToTable("freelancers", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Freelance.PortfolioItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("file_url");

                    b.Property<Guid>("FreelancerId")
                        .HasColumnType("uuid")
                        .HasColumnName("freelancer_id");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_portfolio_items");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_portfolio_items_created_by");

                    b.HasIndex("FreelancerId")
                        .HasDatabaseName("ix_portfolio_items_freelancer_id");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("ix_portfolio_items_modified_by");

                    b.ToTable("portfolio_items", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Languages.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_languages");

                    b.ToTable("languages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 2,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 3,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 4,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 5,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 6,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 7,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 8,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 9,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 10,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 11,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 12,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 13,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 14,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 15,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 16,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 17,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 18,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 19,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 20,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 21,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 22,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 23,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 24,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 25,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 26,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 27,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 28,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 29,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 30,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 31,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 32,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 33,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 34,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 35,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 36,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 37,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 38,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 39,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 40,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 41,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 42,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 43,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 44,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 45,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 46,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 47,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 48,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 49,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 50,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 51,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 52,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 53,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 54,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 55,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 56,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 57,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 58,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 59,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 60,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 61,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 62,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 63,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 64,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 65,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 66,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 67,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 68,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 69,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 70,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 71,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 72,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 73,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 74,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 75,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 76,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 77,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 78,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 79,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 80,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 81,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 82,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 83,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 84,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 85,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 86,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 87,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 88,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 89,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 90,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 91,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 92,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 93,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 94,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 95,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 96,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 97,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 98,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 99,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 100,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 101,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 102,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 103,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 104,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 105,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 106,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 107,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 108,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 109,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 110,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 111,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 112,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 113,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 114,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 115,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 116,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 117,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 118,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 119,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 120,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 121,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 122,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 123,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 124,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 125,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 126,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 127,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 128,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 129,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 130,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 131,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 132,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 133,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 134,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 135,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 136,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 137,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 138,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 139,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 140,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 141,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 142,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 143,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 144,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 145,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 146,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 147,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 148,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 149,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 150,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 151,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 152,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 153,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 154,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 155,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 156,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 157,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 158,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 159,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 160,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 161,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 162,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 163,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 164,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 165,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 166,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 167,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 168,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 169,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 170,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 171,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 172,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 173,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 174,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 175,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 176,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 177,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 178,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 179,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 180,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 181,
                            Code = "",
                            Name = ""
                        },
                        new
                        {
                            Id = 182,
                            Code = "",
                            Name = ""
                        });
                });

            modelBuilder.Entity("Domain.Models.Messaging.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid")
                        .HasColumnName("receiver_id");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("ix_messages_contract_id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_messages_created_by");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("ix_messages_modified_by");

                    b.HasIndex("ReceiverId")
                        .HasDatabaseName("ix_messages_receiver_id");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Payments.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("stripe_payment_intent_id");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("ix_payments_contract_id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_payments_created_by");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("ix_payments_modified_by");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Projects.Bid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("FreelancerId")
                        .HasColumnType("uuid")
                        .HasColumnName("freelancer_id");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("pk_bids");

                    b.HasIndex("FreelancerId")
                        .HasDatabaseName("ix_bids_freelancer_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_bids_project_id");

                    b.ToTable("bids", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Projects.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("BudgetMax")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("budget_max");

                    b.Property<decimal?>("BudgetMin")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("budget_min");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("Deadline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_projects_created_by");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("ix_projects_modified_by");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Projects.ProjectMilestone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_project_milestones");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_project_milestones_created_by");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("ix_project_milestones_modified_by");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_milestones_project_id");

                    b.ToTable("project_milestones", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Projects.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("FreelancerId")
                        .HasColumnType("uuid")
                        .HasColumnName("freelancer_id");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("pk_quotes");

                    b.HasIndex("FreelancerId")
                        .HasDatabaseName("ix_quotes_freelancer_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_quotes_project_id");

                    b.ToTable("quotes", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Projects.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_skills");

                    b.ToTable("skills", (string)null);
                });

            modelBuilder.Entity("FreelancerLanguage", b =>
                {
                    b.Property<Guid>("FreelancerId")
                        .HasColumnType("uuid")
                        .HasColumnName("freelancer_id");

                    b.Property<int>("LanguagesId")
                        .HasColumnType("integer")
                        .HasColumnName("languages_id");

                    b.HasKey("FreelancerId", "LanguagesId")
                        .HasName("pk_freelancers_languages");

                    b.HasIndex("LanguagesId")
                        .HasDatabaseName("ix_freelancers_languages_languages_id");

                    b.ToTable("freelancers_languages", (string)null);
                });

            modelBuilder.Entity("FreelancerSkill", b =>
                {
                    b.Property<Guid>("FreelancerId")
                        .HasColumnType("uuid")
                        .HasColumnName("freelancer_id");

                    b.Property<int>("SkillsId")
                        .HasColumnType("integer")
                        .HasColumnName("skills_id");

                    b.HasKey("FreelancerId", "SkillsId")
                        .HasName("pk_freelancers_skills");

                    b.HasIndex("SkillsId")
                        .HasDatabaseName("ix_freelancers_skills_skills_id");

                    b.ToTable("freelancers_skills", (string)null);
                });

            modelBuilder.Entity("CategoryProject", b =>
                {
                    b.HasOne("Domain.Models.Projects.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_projects_categories_categories_categories_id");

                    b.HasOne("Domain.Models.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_projects_categories_projects_project_id");
                });

            modelBuilder.Entity("Domain.Models.Auth.RefreshToken", b =>
                {
                    b.HasOne("Domain.Models.Auth.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");
                });

            modelBuilder.Entity("Domain.Models.Auth.Users.User", b =>
                {
                    b.HasOne("Domain.Models.Auth.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_users_created_by");

                    b.HasOne("Domain.Models.Auth.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_users_modified_by");

                    b.HasOne("Domain.Models.Auth.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_roles_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Models.Auth.Users.UserWallet", b =>
                {
                    b.HasOne("Domain.Models.Auth.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_wallets_users_created_by");

                    b.HasOne("Domain.Models.Auth.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_wallets_users_modified_by");
                });

            modelBuilder.Entity("Domain.Models.Auth.Users.WalletTransaction", b =>
                {
                    b.HasOne("Domain.Models.Auth.Users.UserWallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wallet_transactions_user_wallets_wallet_id");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Domain.Models.Freelance.Contract", b =>
                {
                    b.HasOne("Domain.Models.Auth.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_contracts_users_created_by");

                    b.HasOne("Domain.Models.Freelance.Freelancer", "Freelancer")
                        .WithMany()
                        .HasForeignKey("FreelancerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contracts_freelancers_freelancer_id");

                    b.HasOne("Domain.Models.Auth.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_contracts_users_modified_by");

                    b.HasOne("Domain.Models.Projects.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contracts_project_project_id");

                    b.Navigation("Freelancer");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Domain.Models.Freelance.ContractMilestone", b =>
                {
                    b.HasOne("Domain.Models.Freelance.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contract_milestones_contracts_contract_id");

                    b.HasOne("Domain.Models.Auth.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_contract_milestones_users_created_by");

                    b.HasOne("Domain.Models.Auth.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_contract_milestones_users_modified_by");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("Domain.Models.Freelance.Freelancer", b =>
                {
                    b.HasOne("Domain.Models.Countries.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_freelancers_country_country_id");

                    b.HasOne("Domain.Models.Auth.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_freelancers_users_created_by");

                    b.HasOne("Domain.Models.Auth.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_freelancers_users_modified_by");

                    b.HasOne("Domain.Models.Auth.Users.User", "User")
                        .WithOne()
                        .HasForeignKey("Domain.Models.Freelance.Freelancer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_freelancers_users_user_id");

                    b.Navigation("Country");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.Freelance.PortfolioItem", b =>
                {
                    b.HasOne("Domain.Models.Auth.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_portfolio_items_users_created_by");

                    b.HasOne("Domain.Models.Freelance.Freelancer", "Freelancer")
                        .WithMany("Portfolio")
                        .HasForeignKey("FreelancerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_portfolio_items_freelancers_freelancer_id");

                    b.HasOne("Domain.Models.Auth.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_portfolio_items_users_modified_by");

                    b.Navigation("Freelancer");
                });

            modelBuilder.Entity("Domain.Models.Messaging.Message", b =>
                {
                    b.HasOne("Domain.Models.Freelance.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_messages_contracts_contract_id");

                    b.HasOne("Domain.Models.Auth.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_messages_users_created_by");

                    b.HasOne("Domain.Models.Auth.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_messages_users_modified_by");

                    b.HasOne("Domain.Models.Auth.Users.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_messages_users_receiver_id");

                    b.Navigation("Contract");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("Domain.Models.Payments.Payment", b =>
                {
                    b.HasOne("Domain.Models.Freelance.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payments_contracts_contract_id");

                    b.HasOne("Domain.Models.Auth.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_payments_users_created_by");

                    b.HasOne("Domain.Models.Auth.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_payments_users_modified_by");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("Domain.Models.Projects.Bid", b =>
                {
                    b.HasOne("Domain.Models.Freelance.Freelancer", "Freelancer")
                        .WithMany()
                        .HasForeignKey("FreelancerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bids_freelancers_freelancer_id");

                    b.HasOne("Domain.Models.Projects.Project", "Project")
                        .WithMany("Bids")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bids_project_project_id");

                    b.Navigation("Freelancer");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Domain.Models.Projects.Project", b =>
                {
                    b.HasOne("Domain.Models.Auth.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_projects_users_created_by");

                    b.HasOne("Domain.Models.Auth.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_projects_users_modified_by");
                });

            modelBuilder.Entity("Domain.Models.Projects.ProjectMilestone", b =>
                {
                    b.HasOne("Domain.Models.Auth.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_project_milestones_users_created_by");

                    b.HasOne("Domain.Models.Auth.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_project_milestones_users_modified_by");

                    b.HasOne("Domain.Models.Projects.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_milestones_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Domain.Models.Projects.Quote", b =>
                {
                    b.HasOne("Domain.Models.Freelance.Freelancer", "Freelancer")
                        .WithMany()
                        .HasForeignKey("FreelancerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quotes_freelancers_freelancer_id");

                    b.HasOne("Domain.Models.Projects.Project", "Project")
                        .WithMany("Quotes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quotes_projects_project_id");

                    b.Navigation("Freelancer");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("FreelancerLanguage", b =>
                {
                    b.HasOne("Domain.Models.Freelance.Freelancer", null)
                        .WithMany()
                        .HasForeignKey("FreelancerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_freelancers_languages_freelancers_freelancer_id");

                    b.HasOne("Domain.Models.Languages.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_freelancers_languages_language_languages_id");
                });

            modelBuilder.Entity("FreelancerSkill", b =>
                {
                    b.HasOne("Domain.Models.Freelance.Freelancer", null)
                        .WithMany()
                        .HasForeignKey("FreelancerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_freelancers_skills_freelancers_freelancer_id");

                    b.HasOne("Domain.Models.Projects.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_freelancers_skills_skill_skills_id");
                });

            modelBuilder.Entity("Domain.Models.Freelance.Freelancer", b =>
                {
                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("Domain.Models.Projects.Project", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("Quotes");
                });
#pragma warning restore 612, 618
        }
    }
}
